### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dr0i** [skohub-io/skohub-editor#56]
Working on [updating dependencies](https://github.com/skohub-io/skohub-editor/network/alerts) I ran `npm test`, but that gave thousands of errors. Do I understand this correctly - there are no tests, so `npm test` shouldn't be executed?

**Comment by literarymachine** [comment]
`npm test` currently only does linter checks, and those were not properly configured. https://github.com/skohub-io/skohub-editor/pull/59 fixes that.

**Comment by dr0i** [comment]
The errors disappeared :) However, the output of `npm test` is just empty (besides "Warning: React version not specified in eslint-plugin-react settings."). Is this expected behaviour?

**Comment by literarymachine** [comment]
Yep!

**Comment by dr0i** [comment]
Ok, thx! Closed.
